kind: pipeline
type: exec
name: backend

platform:
  os: darwin
  arch: amd64

clone:
  disable: true

steps:
- name: greeting
  commands:
  - echo hello backend

---
kind: pipeline
type: exec
name: frontend

platform:
  os: darwin
  arch: amd64

clone:
  disable: true

steps:
- name: greeting
  commands:
  - echo hello frontend

---
kind: pipeline
type: exec
name: final

platform:
  os: darwin
  arch: amd64

clone:
  disable: true

steps:
- name: final
  commands:
  - echo "The previous tasks have been completed"

depends_on:
- backend
- frontend