kind: pipeline
type: exec
name: greeting2

platform:
  os: darwin
  arch: amd64

clone:
  disable: true

steps:
- name: greeting
  commands:
  - echo hello world
  - say "你好呀"

- name: greeting2
  commands:
  - echo hello world2
  - say "哈哈哈哈哈"